### ISSUE TITLE
redstone.xmlrpc.XmlRpcFault: You do not have permissions to perform this action.

### ISSUE THREAD

**Issue by hossman-12** [stevemeier/cefs#34]
I'm trying to import Errata for Cent 8 using the following command
/usr/local/centos/errata-import.pl --server 'xxxx' --errata /usr/local/centos/errata.latest.xml  --include-channels=centos8-x86_64  --publish --rhsa-oval /usr/local/centos/com.redhat.rhsa-all.xml --debug

It starts to import but fails.

INFO: Adding packages to CEBA-2020:5464:
DEBUG: Processing CEBA-2020:5465
INFO: Errata for CEBA-2020:5465 already exists
DEBUG: list_packages: CEBA-2020:5465 98294 98394 98434 98534 121777 121852 121900 122045
DEBUG: Package: 389-ds-base-1.3.10.2-8.el7_9.src.rpm not found
DEBUG: Package: 389-ds-base-1.3.10.2-8.el7_9.x86_64.rpm not found
DEBUG: Package: 389-ds-base-devel-1.3.10.2-8.el7_9.x86_64.rpm not found
DEBUG: Package: 389-ds-base-libs-1.3.10.2-8.el7_9.x86_64.rpm not found
DEBUG: Package: 389-ds-base-snmp-1.3.10.2-8.el7_9.x86_64.rpm not found
DEBUG: find_packages advisory: CEBA-2020--5465
DEBUG: find_packages packages:
DEBUG: find_packages channels:
INFO: Adding packages to CEBA-2020:5465:
DEBUG: Processing CEBA-2020:5472
INFO: Errata for CEBA-2020:5472 already exists
DEBUG: list_packages: CEBA-2020:5472 124407 124447 124507 124527 124547 124587 126395 126428 126505
DEBUG: Package: tuned-2.14.0-3.el8_3.1.noarch.rpm -> 124407 -> centos8-x86_64
DEBUG: Package: tuned-gtk-2.14.0-3.el8_3.1.noarch.rpm not found
DEBUG: Package: tuned-profiles-atomic-2.14.0-3.el8_3.1.noarch.rpm -> 124507 -> centos8-x86_64
DEBUG: Package: tuned-profiles-compat-2.14.0-3.el8_3.1.noarch.rpm -> 124447 -> centos8-x86_64
DEBUG: Package: tuned-profiles-cpu-partitioning-2.14.0-3.el8_3.1.noarch.rpm -> 124547 -> centos8-x86_64
DEBUG: Package: tuned-profiles-mssql-2.14.0-3.el8_3.1.noarch.rpm -> 124587 -> centos8-x86_64
DEBUG: Package: tuned-profiles-oracle-2.14.0-3.el8_3.1.noarch.rpm -> 124527 -> centos8-x86_64
DEBUG: Package: tuned-utils-2.14.0-3.el8_3.1.noarch.rpm not found
DEBUG: Package: tuned-utils-systemtap-2.14.0-3.el8_3.1.noarch.rpm not found
DEBUG: find_packages advisory: CEBA-2020--5472
DEBUG: find_packages packages: 124547,124447,124587,124507,124527,124407
DEBUG: find_packages channels: centos8-x86_64
INFO: Adding packages to CEBA-2020:5472: 124547,124447,124587,124507,124527,124407
INFO: Republishing CEBA-2020:5472
DEBUG: Republishing CEBA-2020:5472 to channel centos8-x86_64
Fault returned from XML RPC Server, fault code -23: redstone.xmlrpc.XmlRpcFault: You do not have permissions to perform this action.

I can import Cent 7 data with out issue

/usr/local/centos/errata-import.pl --server 'xxxxx'  --errata /usr/local/centos/errata.latest.xml  --include-channels=centos7-updates-x86_64,centos7-x86_64 --publish --rhsa-oval /usr/local/centos/com.redhat.rhsa-RHEL7.xml

I'm running version 20210501

**Comment by stevemeier** [comment]
What server type and version are you using? Spacewalk, Uyuni, SuSE Manager?

Does the account have "Channel Administrator" rights on both channels?

**Comment by hossman-12** [comment]
Suse Manager.

The Account I'm using is the Main Admin account I created at install.  It does have Channel Admin rights and it does have manager rights when I check the individual Channels.

Here is a snipit from the rhn_web_api.log.   It was working and then failed.
[2021-06-02 14:23:30,990] INFO  - REQUESTED FROM: ###.###.###.### CALL: errata.applicable_to_channels(USERNAME, CEBA-2020:5459) CALLER: (USERNAME) TIME: 0.018 seconds
[2021-06-02 14:23:31,010] INFO  - REQUESTED FROM: ###.###.###.### CALL: errata.listPackages(USERNAME, CEBA-2020:5460) CALLER: (USERNAME) TIME: 0.01 seconds
[2021-06-02 14:23:31,032] INFO  - REQUESTED FROM: ###.###.###.### CALL: errata.add_packages(USERNAME, CEBA-2020:5460, []) CALLER: (USERNAME) TIME: 0.002 seconds
[2021-06-02 14:23:31,051] INFO  - REQUESTED FROM: ###.###.###.### CALL: errata.applicable_to_channels(USERNAME, CEBA-2020:5460) CALLER: (USERNAME) TIME: 0.013 seconds
[2021-06-02 14:23:31,145] INFO  - REQUESTED FROM: ###.###.###.### CALL: errata.listPackages(USERNAME, CEBA-2020:5461) CALLER: (USERNAME) TIME: 0.087 seconds
[2021-06-02 14:23:31,180] INFO  - REQUESTED FROM: ###.###.###.### CALL: errata.add_packages(USERNAME, CEBA-2020:5461, []) CALLER: (USERNAME) TIME: 0.002 seconds
[2021-06-02 14:23:31,202] INFO  - REQUESTED FROM: ###.###.###.### CALL: errata.applicable_to_channels(USERNAME, CEBA-2020:5461) CALLER: (USERNAME) TIME: 0.016 seconds
[2021-06-02 14:23:31,238] INFO  - REQUESTED FROM: ###.###.###.### CALL: errata.listPackages(USERNAME, CEBA-2020:5464) CALLER: (USERNAME) TIME: 0.026 seconds
[2021-06-02 14:23:31,258] INFO  - REQUESTED FROM: ###.###.###.### CALL: errata.add_packages(USERNAME, CEBA-2020:5464, []) CALLER: (USERNAME) TIME: 0.002 seconds
[2021-06-02 14:23:31,280] INFO  - REQUESTED FROM: ###.###.###.### CALL: errata.applicable_to_channels(USERNAME, CEBA-2020:5464) CALLER: (USERNAME) TIME: 0.017 seconds
[2021-06-02 14:23:31,303] INFO  - REQUESTED FROM: ###.###.###.### CALL: errata.listPackages(USERNAME, CEBA-2020:5465) CALLER: (USERNAME) TIME: 0.012 seconds
[2021-06-02 14:23:31,318] INFO  - REQUESTED FROM: ###.###.###.### CALL: errata.add_packages(USERNAME, CEBA-2020:5465, []) CALLER: (USERNAME) TIME: 0.001 seconds
[2021-06-02 14:23:31,340] INFO  - REQUESTED FROM: ###.###.###.### CALL: errata.applicable_to_channels(USERNAME, CEBA-2020:5465) CALLER: (USERNAME) TIME: 0.016 seconds
[2021-06-02 14:23:31,363] INFO  - REQUESTED FROM: ###.###.###.### CALL: errata.listPackages(USERNAME, CEBA-2020:5472) CALLER: (USERNAME) TIME: 0.014 seconds
[2021-06-02 14:23:31,418] INFO  - REQUESTED FROM: ###.###.###.### CALL: errata.add_packages(USERNAME, CEBA-2020:5472, [124547, 124407, 124527, 124507, 124587, 124447]) CALLER: (distsysa
dmin) TIME: 0.042 seconds
[2021-06-02 14:23:31,440] INFO  - REQUESTED FROM: ###.###.###.### CALL: errata.applicable_to_channels(USERNAME, CEBA-2020:5472) CALLER: (USERNAME) TIME: 0.011 seconds
[2021-06-02 14:23:31,460] ERROR - REQUESTED FROM: ###.###.###.### CALL: errata.publish(USERNAME, CEBA-2020:5472, [centos8-x86_64]) CALLER: (USERNAME) TIME: 0.013 seconds
redstone.xmlrpc.XmlRpcFault: You do not have permissions to perform this action.
        at com.redhat.rhn.frontend.xmlrpc.ExceptionTranslator.translateException(ExceptionTranslator.java:44)
        at com.redhat.rhn.frontend.xmlrpc.BaseHandler.invoke(BaseHandler.java:169)
        at redstone.xmlrpc.XmlRpcDispatcher.dispatch(XmlRpcDispatcher.java:123)
        at com.redhat.rhn.frontend.xmlrpc.RhnXmlRpcServer.execute(RhnXmlRpcServer.java:54)
        at com.redhat.rhn.frontend.xmlrpc.XmlRpcServlet.doPost(XmlRpcServlet.java:165)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.opensymphony.module.sitemesh.filter.PageFilter.parsePage(PageFilter.java:142)
        at com.opensymphony.module.sitemesh.filter.PageFilter.doFilter(PageFilter.java:58)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.LocalizedEnvironmentFilter.doFilter(LocalizedEnvironmentFilter.java:70)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.EnvironmentFilter.doFilter(EnvironmentFilter.java:103)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.SessionFilter.doFilter(SessionFilter.java:55)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:97)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:432)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1591)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by stevemeier** [comment]
Ok, that's a SuSE Manager issue, not a script issue.

Please follow see here -> https://github.com/stevemeier/cefs/issues/12#issuecomment-717987374

**Comment by hossman-12** [comment]
This resolved my issue.  
Thank You.
