### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by Slper** [stevemeier/cefs#6]
get error while trying to update errata with errata-import.pl script called as

./errata-import.pl --server IP_addr --errata errata.latest.xml --include-channels=cent6-64 --bugfix --security --enhancement --publish --quiet --debug

**Comment by stevemeier** [comment]
Please provide the full debug output.
With the information provided, I can not do anything.

**Comment by Slper** [comment]
# ./errata-import.pl --server IP_addr --errata errata.latest.xml --rhsa-oval com.redhat.rhsa-all.xml --include-channels="cent6-64" --publish
503 Service Unavailable
#

this is all i got after run script

**Comment by stevemeier** [comment]
Well, this is an error from the Spacewalk API, so you need to look into your Spacewalk server.

**Comment by Slper** [comment]
Spacewalk is up and running. could you please suggest where should i check?

**Comment by stevemeier** [comment]
Have a look at /var/log/rhn/rhn_web_api.log, which is the API log.
Or contact the Spacewalk Mailing list for help -> https://www.redhat.com/mailman/listinfo/spacewalk-list

**Comment by Slper** [comment]
error from log file is 

[2018-05-03 15:34:19,864] ERROR - REQUESTED FROM: ::1 CALL: errata.getDetails(Admin, CESA-2105--X001) CALLER: (Admin) TIME: 0.006 seconds
redstone.xmlrpc.XmlRpcFault: The errata CESA-2105--X001 cannot be found.

i dowloaded errata from https://cefs.steve-meier.de/errata.latest.xml

**Comment by stevemeier** [comment]
There is a lot more data in that log. The script should also output a log when run with --debug.
Without more data it's impossible to know, why your setup is not working.

**Comment by Slper** [comment]
[2018-05-03 15:34:19,864] ERROR - REQUESTED FROM: ::1 CALL: errata.getDetails(Admin, CESA-2105--X001) CALLER: (Admin) TIME: 0.006 seconds
redstone.xmlrpc.XmlRpcFault: The errata CESA-2105--X001 cannot be found.
        at com.redhat.rhn.frontend.xmlrpc.BaseHandler.invoke(BaseHandler.java:171)
        at redstone.xmlrpc.XmlRpcDispatcher.dispatch(XmlRpcDispatcher.java:123)
        at com.redhat.rhn.frontend.xmlrpc.RhnXmlRpcServer.execute(RhnXmlRpcServer.java:54)
        at com.redhat.rhn.frontend.xmlrpc.XmlRpcServlet.doPost(XmlRpcServlet.java:162)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:643)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
        at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at com.redhat.rhn.frontend.servlets.LocalizedEnvironmentFilter.doFilter(LocalizedEnvironmentFilter.java:67)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at com.redhat.rhn.frontend.servlets.EnvironmentFilter.doFilter(EnvironmentFilter.java:101)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at com.redhat.rhn.frontend.servlets.SessionFilter.doFilter(SessionFilter.java:57)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at com.redhat.rhn.frontend.servlets.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:97)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:299)
        at org.apache.jk.server.JkCoyoteHandler.invoke(JkCoyoteHandler.java:190)
        at org.apache.jk.common.HandlerRequest.invoke(HandlerRequest.java:291)
        at org.apache.jk.common.ChannelSocket.invoke(ChannelSocket.java:769)
        at org.apache.jk.common.ChannelSocket.processConnection(ChannelSocket.java:698)
        at org.apache.jk.common.ChannelSocket$SocketConnection.runIt(ChannelSocket.java:891)
        at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:690)
        at java.lang.Thread.run(Thread.java:748)
[2018-05-03 15:34:19,899] INFO  - REQUESTED FROM: ::1 CALL: auth.logout(122xf4cbc73882b1aa8acd860953af69750267ea3a7d48d64b4f8d8309aa089b8928) CALLER: (Admin) TIME: 0.004 seconds

**Comment by Slper** [comment]
It is my proxy problem so i fix script by put no porxy function into it.
